modLoader = "javafml"
loaderVersion = "[40,)"
license = "LGPL-3.0 License"
issueTrackerURL = "https://github.com/Janoeo/Foundation/issues"
[[mods]]
modId = "janoeo_foundation"
version = "${file.jarVersion}"
displayName = "Janoeo Foundation"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/janoeo"
logoFile = "janoeo_foundation.png"
itemIcon = "janoeo_foundation:iron_dust"
authors = "AlasDiablo, Safyrus, SmartzyYY"
description = '''
This mod a lot of ore type and more!
'''

[[dependencies.janoeo_foundation]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.janoeo_foundation]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.janoeo_foundation]]
modId = "diolib"
mandatory = true
versionRange = "[4.4.25,)"
ordering = "NONE"
side = "BOTH"
