modLoader = "javafml"
loaderVersion = "[46,)"
license = "LGPL-3.0 License"
issueTrackerURL = "https://github.com/Janoeo/Foundation/issues"
[[mods]]
    modId = "janoeo_foundation"
    version = "${file.jarVersion}"
    displayName = "Janoeo Foundation"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/janoeo"
    itemIcon = "janoeo_foundation:iron_dust"
    authors = "AlasDiablo, Safyrus, SmartzyYY"
    description = '''
    This mod a lot of ore type and more!
    '''

[[dependencies.janoeo_foundation]]
    modId = "forge"
    mandatory = true
    versionRange = "[46,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.janoeo_foundation]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20,1.21)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.janoeo_foundation]]
    modId = "diolib"
    mandatory = true
    versionRange = "[6.7.32,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.janoeo_foundation]]
    modId = "worldstripper"
    mandatory = false
    versionRange = "[3.3.0,)"
    ordering = "NONE"
    side = "BOTH"
