name: Run build

on:
  push:
    branches: [ '1.18', '1.18.2' ]
  pull_request:
    branches: [ '1.18', '1.18.2' ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission
        shell: bash
        run: |
          chmod +x gradlew
          chmod +x ./.github/workflows/setkey.sh

      - name: Update mod version
        shell: bash
        run: ./.github/workflows/setkey.sh ${{github.run_number}}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Generated mod data
        uses: gradle/gradle-build-action@v2
        with:
          arguments: runData

      - name: Build mod
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Upload mod build
        uses: actions/upload-artifact@v2
        with:
          name: janoeo-foundation
          path: output/*
