name: Run build

on:
  push:
    branches: [ '1.18', '1.18.2' ]
  pull_request:
    branches: [ '1.18', '1.18.2' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Set gradle ci information
        shell: bash
        run: echo "org.gradle.jvmargs=-Xmx3G\norg.gradle.daemon=false\nci_build=true\nci_build_number=${{github.run_number}}" > gradle.properties
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload ci build
        uses: actions/upload-artifact@v2
        with:
          name: janoeo-foundation
          path: output/*
